name: Deploy and Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Atualizando repositório
        uses: actions/checkout@v2

      - name: Criando o ambiente
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Instalando dependências
        run: npm install

      - name: Gerando o projeto
        run: npm run build

      - name: Atualizando arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: public_html/
          git-ftp-args: --insecure

      - name: Criando o release/tag
        permissions: write-all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
