name: Deploy and Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Atualizando repositório
        uses: actions/checkout@v2

      - name: Criando o ambiente
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Instalando dependências
        run: npm install

      - name: Gerando o projeto
        run: npm run build

      - name: Atualizando arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: public_html/
          git-ftp-args: --insecure

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
